version: 0.2
env:
  variables:
    CI_ENGINE: "CodeBuild"
phases:
  install:
    commands:
      - make -j -C provision/build buildenv debuginfo
  build:
    commands:
      - make -j tar
artifacts:
  files:
    - 'target/*.tar.gz'
    - 'target/*.txt'
    - 'packages/s3proxy/target/*.txt'
  discard-paths: yes
