version: 0.2
phases:
  install:
    commands:
      - make -j -C provision/build buildenv debuginfo
  build:
    commands:
      - make -j test tar
artifacts:
  files:
    - 'target/*.tar.gz'
    - 'target/test-*'
    - 'target/packages/s3proxy/target/test-*'
