version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - make -j tar
  artifacts:
    files:
      - '*.tar.gz'
      - 'test-*'
    discard-paths: yes
    base-directory: target
