name: Docker Build and Push
on:
  release:
    types:
      - created
jobs:
  dockerize:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONTENT_TRUST: 0
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: docker build and push to aws
        env:
          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        run: |
          npm run package
          npm run docker-login-aws
          npm run dockerize-for-prod-aws
      - name: docker build and push to dockerhub
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        run: |
          npm run docker-login-dockerhub
          npm run dockerize-for-prod-dockerhub

