name: Docker Build
on: [push, pull_request]
jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: actions/checkout@v2
      - name: Install syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: docker
        run: |
          npm run package
          npm run software-bill-of-materials